# Generated by Django 4.2.6 on 2023-10-25 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car_delete_prodcate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
